### ISSUE TITLE
Add Mehr Nastaleeq font

### ISSUE THREAD

**Issue by alicewriteswrongs** [basshelal/Wudooh#10]
In my humble opinion this is the most beautiful Nastaliq font for the web, it would be great to use it with this extension! There is a "nastaleeq" extension which adds this font for some sites like BBC Urdu: https://chrome.google.com/webstore/detail/nastaleeq/oddbjmjgpaofommagnbfednbdifaakfb

I think the website for the font is here: http://csalt.itu.edu.pk/urdufont/

**Comment by basshelal** [comment]
@aliceriot Hey, thanks for your feedback and your interest in helping out!
I'll definitely add the font in the next update that I'm currently working on, I'll let you know when it's released!
Many thanks!

**Comment by basshelal** [comment]
I've added Mehr Nastaliq to the repo, should be available to use in the next update (I'll let you know when it's released).

However I did notice that there is very little visible difference between Mehr and Urdu Typesetting which Wudooh currently has.

Urdu Typesetting called اُردُو‎  in Wudooh:
![Urdu](https://user-images.githubusercontent.com/23533612/63130442-602a9c80-bfb2-11e9-9bf6-872638afde0d.PNG)

Mehr Nastaliq:
![Mehr](https://user-images.githubusercontent.com/23533612/63130464-720c3f80-bfb2-11e9-87d2-450a3f4de535.PNG)

Of course I'm no expert and I just picked a random piece of text so maybe the differences aren't visible here to me.

So you could use Urdu Typesetting until the new update comes out with Mehr and many others (I plan on getting a LOT more fonts).

Anyway thanks again for the suggestion, closing because it's been added.
