### ISSUE TITLE
Google Docs cursor is broken by Wudooh during editing.

### ISSUE THREAD

**Issue by orehmane** [basshelal/Wudooh#15]
I'm editing mixed English and Arabic in a single Google Doc - when they appear in the same sentence, the visual location of the cursor becomes offset from where the cursor actually is, making editing more difficult.

I believe this has to do with how the size of the Arabic font is changed. Is there a feasible solution to this?

Thank you again for your work!

**Comment by basshelal** [comment]
Hey there, thanks for using Wudooh and giving your feedback, it means a lot to me 😊.

This is actually one of the main reasons I added the whitelist and on/off switch features. Every website renders and handles text and text changes differently, and so there are some websites that just don't work well or even at all, a good example is YouTube, which has been the reason for countless sleepless nights and fits of rage and anger (see #7 ), they do things so differently from anyone else I think it's almost impossible to make Wudooh work perfectly on it unless *they* change it.
A similar thing is on Quran.com which renders characters completely differently, that Wudooh actually ***breaks*** the site.

Unfortunately there's not much I can do for these outlier websites, that's the reason for the whitelist function, so that at least Wudooh won't break the site, it'll just not run on it any more giving back the default appearance. It's not ideal, but no change is better than breaking changes.

I'm sorry that I can't help more with this, I am aware of some of these outlier sites (I knew Google Docs was one of them, YouTube is the biggest problem) but they have nothing really in common that *I* can see.

Sorry I couldn't be of much help but thanks for your feedback and kind words 😊

Many thanks and peace to you 😊

**Comment by orehmane** [comment]
That's a shame. If you have time to create a specific exception for Google Docs, that would be great - I unfortunately don't have any time to take on new projects at the moment. But it is still usable, so thanks again!
