### ISSUE TITLE
Add export and import settings

### ISSUE THREAD

**Issue by chiinau** [basshelal/Wudooh#4]
Hey,
Thanks for this great extension !
I have a question about the white listing functionality. Is it exportable in case of wanting to change the browser?

**Comment by AmenJlili** [comment]
I think it would be even better to allow users to whitelist pages using a regex instead of the domain. This can be on top of the current feature.

**Comment by basshelal** [comment]
@chiinau Hey, thanks a lot for your appreciation, I hope this has helped you in some way.
Unfortunately, I the whitelist isn't exportable and allowing this would be a little tricky.
The whitelist, as do all settings of the extension, work by using the [browser's storage sync](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/sync) which is used across instances of the same browser. So chrome will have the same settings across your devices using your Google account but cannot transfer this to Firefox. [Here's the exact line where whitelisting is done, if you're interested](https://github.com/basshelal/Wudooh/blob/2ce39b7cd813593e95b40b5df10994bc7f37da8f/chrome/popup.ts#L178). 

This would be a tricky feature to implement, it would have to make the user first export their whitelist from one browser into a JSON file, then open up the other browser and import the whitelist into that browser. It's definitely not impossible but it opens up a lot of potential bugs and security problems during the import step, as the user could provide some corrupt or unknown file, strong preemptive measures would have to be taken.

I'll definitely consider the feature, but unless more people request it, it's not a big priority right now.

**Comment by basshelal** [comment]
This feature is basically done! Just needs more testing and tweaking but it's currently deliverable.

Users will now be able to import and export their settings, meaning that you can transfer your settings between browsers. This is even cooler and more necessary than before because I do plan on adding Edge and Opera support (see #13) , meaning hopefully Wudooh will support **FOUR** browsers! (fingers crossed 🤞 everything works well).

The user exports and imports a JSON file called `settings.wudooh.json` (it can have any name really) which will contain all the settings of the extension. Here's an example:
```json
{
    "font": "Droid Arabic Naskh",
    "lineHeight": 125,
    "onOff": true,
    "textSize": 125,
    "whitelisted": [
        "www.twitch.tv",
        "twitter.com"
    ],
    "customSettings": [
        {
            "font": "Noto Naskh Arabic",
            "lineHeight": 125,
            "textSize": 125,
            "url": "reddit.com"
        },
        {
            "font": "Droid Arabic Naskh",
            "lineHeight": 125,
            "textSize": 125,
            "url": "www.youtube.com"
        }
    ]
}
```

It's all mostly self-explanatory but I am considering making a new page on the site as a documentation or guide for potentially confused users.

The main thing though is that the import operation does actually check for valid fields, and will not accept a file with missing or invalid fields, so it is very strict on what it accepts. The export operation exports **all** settings from the browser storage, so it's also a great tool to find errors and fix them (such as duplicated sites or something like that, shouldn't happen I've made sure of it, but just in case).

I'm not going to close this just yet, but the feature is basically done.

Exciting stuff! 😊

**Comment by basshelal** [comment]
This is done and tested! 😊
All settings can be exported and imported and validation is strict.
All that's needed is a page on the site as a guide for users but that should be easy enough.
Closing 😊
